### ISSUE TITLE
Visual Examples are Incorrect and Misleading

### ISSUE THREAD

**Issue by Myndex** [xi/apca-introduction#18] opened 2022-09-10 20:19 UTC
The visual examples shown in the "introduction" are incorrect and particularly misleading, as they are using incorrect font sizes and weights, and therefore are nut actually comparing APCA to WCAG.

This problem was corrected in pull request #11, but that was closed without being merged.

**Comment by xi** [comment] 2022-09-10 20:58
Duplicate of #5. Please check existing issues before opening new ones.

**Closed by xi** 2022-09-10 20:58 UTC

**Comment by Myndex** [comment] 2022-09-12 17:56
Not a duplicate, as herein I posted a link to the corrected examples.

### The proper visual examples can be seen at the [corrected fork of this repo](https://github.com/Myndex/apca-introduction/blob/main/README.md)
